artifacts_config:
  artifacts_dir: artifacts

data_ingestion_config:
  dataset_download_url: https://github.com/sudhanvabharadwaj/Datasets/raw/refs/heads/main/Ecommerce-books-data.zip
  dataset_dir: dataset
  ingested_dir: ingested_data
  raw_data_dir: raw_data